import {Tour} from './tour';

export const TOURS: Partial<Tour>[] = [
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 0,
  },
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 1,
  },
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 2,
  },
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 3,
  },
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 4,
  },
  {
    gallery: ['assets/fit-main.png', 'assets/girlsfitt.jpg', 'assets/retro.jpg', 'assets/main.png', 'assets/sea-main.png'],
    name: 'Our first tour',
    start: new Date(),
    end: new Date(),
    fullPrice: 4200,
    discount: 420,
    id: 4,
  },
];
